// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#pragma once

#include <utility>

namespace loginsystem {

struct CheckSessionResponse final {
    bool success;
    bool is_valid;

    CheckSessionResponse(bool success_,
                         bool is_valid_)
    : success(std::move(success_))
    , is_valid(std::move(is_valid_))
    {}
};

}  // namespace loginsystem
