// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#pragma once

#include <utility>

namespace loginsystem {

struct RegisterResponse final {
    bool success;

    RegisterResponse(bool success_)
    : success(std::move(success_))
    {}
};

}  // namespace loginsystem
