# This file is generated by gyp; do not edit.

include $(CLEAR_VARS)

LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE := libloginsystem_jni
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_TARGET_ARCH := $(TARGET_$(GYP_VAR_PREFIX)ARCH)
LOCAL_SDK_VERSION := 19
gyp_intermediate_dir := $(call local-intermediates-dir,,$(GYP_VAR_PREFIX))
gyp_shared_intermediate_dir := $(call intermediates-dir-for,GYP,shared,,,$(GYP_VAR_PREFIX))

# Make sure our deps are built first.
GYP_TARGET_DEPENDENCIES := \
	$(call intermediates-dir-for,STATIC_LIBRARIES,djinni_jni,,,$(GYP_VAR_PREFIX))/djinni_jni.a

GYP_GENERATED_OUTPUTS :=

# Make sure our deps and generated files are built first.
LOCAL_ADDITIONAL_DEPENDENCIES := $(GYP_TARGET_DEPENDENCIES) $(GYP_GENERATED_OUTPUTS)

LOCAL_GENERATED_SOURCES :=

GYP_COPIED_SOURCE_ORIGIN_DIRS :=

LOCAL_SRC_FILES := \
	deps/djinni/support-lib/jni/djinni_main.cpp \
	generated-src/jni/NativeServerClient.cpp \
	generated-src/jni/NativeCheckSessionResponse.cpp \
	generated-src/jni/NativeRegisterResponse.cpp \
	generated-src/jni/NativeLoginResponse.cpp \
	handwritten-src/cpp/server_client_impl.cpp


# Flags passed to both C and C++ files.
MY_CFLAGS_Debug := \
	-gdwarf-2 \
	-Wextra \
	-Wno-missing-field-initializers \
	-L/usr/local/lib \
	$(pkg-config --cflags protobuf) \
	$(pkg-config --libs protobuf) \
	-g \
	-O0 \
	-DDEBUG=1 \
	-L/usr/local/lib

MY_DEFS_Debug := \
	'-DDEBUG=1'


# Include paths placed before CFLAGS/CPPFLAGS
LOCAL_C_INCLUDES_Debug := \
	../../../../../../usr/local/include \
	../../../../../../usr/local/libgenerated-src/jni \
	$(LOCAL_PATH)/generated-src/cpp \
	$(LOCAL_PATH)/handwritten-src/jni \
	$(LOCAL_PATH)/handwritten-src/cpp \
	$(LOCAL_PATH)/deps/djinni/support-lib/jni \
	../../../../../../usr/local/include \
	../../../../../../usr/local/include


# Flags passed to only C++ (and not C) files.
LOCAL_CPPFLAGS_Debug := \
	-std=c++11 \
	-frtti \
	-fexceptions \
	-I/usr/local/include/ \
	-L/usr/local/lib \
	-L/usr/local/lib \
	$(pkg-config --cflags protobuf) \
	$(pkg-config --libs protobuf)


# Flags passed to both C and C++ files.
MY_CFLAGS_Release := \
	-gdwarf-2 \
	-Wextra \
	-Wno-missing-field-initializers \
	-L/usr/local/lib \
	$(pkg-config --cflags protobuf) \
	$(pkg-config --libs protobuf) \
	-Os \
	-fomit-frame-pointer \
	-fdata-sections \
	-ffunction-sections \
	-DNDEBUG=1

MY_DEFS_Release := \
	'-DNDEBUG=1'


# Include paths placed before CFLAGS/CPPFLAGS
LOCAL_C_INCLUDES_Release := \
	../../../../../../usr/local/include \
	../../../../../../usr/local/libgenerated-src/jni \
	$(LOCAL_PATH)/generated-src/cpp \
	$(LOCAL_PATH)/handwritten-src/jni \
	$(LOCAL_PATH)/handwritten-src/cpp \
	$(LOCAL_PATH)/deps/djinni/support-lib/jni \
	../../../../../../usr/local/include \
	../../../../../../usr/local/include


# Flags passed to only C++ (and not C) files.
LOCAL_CPPFLAGS_Release := \
	-std=c++11 \
	-frtti \
	-fexceptions \
	-I/usr/local/include/ \
	-L/usr/local/lib \
	-L/usr/local/lib \
	$(pkg-config --cflags protobuf) \
	$(pkg-config --libs protobuf)


LOCAL_CFLAGS := $(MY_CFLAGS_$(GYP_CONFIGURATION)) $(MY_DEFS_$(GYP_CONFIGURATION))
LOCAL_C_INCLUDES := $(GYP_COPIED_SOURCE_ORIGIN_DIRS) $(LOCAL_C_INCLUDES_$(GYP_CONFIGURATION))
LOCAL_CPPFLAGS := $(LOCAL_CPPFLAGS_$(GYP_CONFIGURATION))
LOCAL_ASFLAGS := $(LOCAL_CFLAGS)
### Rules for final target.

LOCAL_LDFLAGS_Debug := \
	-llog \
	-Wl,--build-id,--gc-sections,--exclude-libs,ALL \
	-D_GLIBCXX_USE_CXX11_ABI=0


LOCAL_LDFLAGS_Release := \
	-llog \
	-Wl,--build-id,--gc-sections,--exclude-libs,ALL \
	-D_GLIBCXX_USE_CXX11_ABI=0

LOCAL_GYP_LIBS :=

LOCAL_LDFLAGS := $(LOCAL_LDFLAGS_$(GYP_CONFIGURATION)) $(LOCAL_GYP_LIBS)

LOCAL_STATIC_LIBRARIES := \
	djinni_jni

# Enable grouping to fix circular references
LOCAL_GROUP_STATIC_LIBRARIES := true
LOCAL_PRELINK_MODULE := false
include $(BUILD_SHARED_LIBRARY)
