// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#pragma once

#include "djinni_support.hpp"
#include "login_response.hpp"

namespace djinni_generated {

class NativeLoginResponse final {
public:
    using CppType = ::loginsystem::LoginResponse;
    using JniType = jobject;

    using Boxed = NativeLoginResponse;

    ~NativeLoginResponse();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeLoginResponse();
    friend ::djinni::JniClass<NativeLoginResponse>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/loginsystem/LoginResponse") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(ZLjava/lang/String;)V") };
    const jfieldID field_mSuccess { ::djinni::jniGetFieldID(clazz.get(), "mSuccess", "Z") };
    const jfieldID field_mSessionId { ::djinni::jniGetFieldID(clazz.get(), "mSessionId", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
