// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#include "NativeCheckSessionResponse.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeCheckSessionResponse::NativeCheckSessionResponse() = default;

NativeCheckSessionResponse::~NativeCheckSessionResponse() = default;

auto NativeCheckSessionResponse::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeCheckSessionResponse>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.success)),
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.is_valid)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeCheckSessionResponse::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeCheckSessionResponse>::get();
    return {::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mSuccess)),
            ::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mIsValid))};
}

}  // namespace djinni_generated
