// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#pragma once

#include "check_session_response.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCheckSessionResponse final {
public:
    using CppType = ::loginsystem::CheckSessionResponse;
    using JniType = jobject;

    using Boxed = NativeCheckSessionResponse;

    ~NativeCheckSessionResponse();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeCheckSessionResponse();
    friend ::djinni::JniClass<NativeCheckSessionResponse>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/loginsystem/CheckSessionResponse") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(ZZ)V") };
    const jfieldID field_mSuccess { ::djinni::jniGetFieldID(clazz.get(), "mSuccess", "Z") };
    const jfieldID field_mIsValid { ::djinni::jniGetFieldID(clazz.get(), "mIsValid", "Z") };
};

}  // namespace djinni_generated
