// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#include "NativeLoginResponse.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeLoginResponse::NativeLoginResponse() = default;

NativeLoginResponse::~NativeLoginResponse() = default;

auto NativeLoginResponse::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeLoginResponse>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.success)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.session_id)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeLoginResponse::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeLoginResponse>::get();
    return {::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mSuccess)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mSessionId))};
}

}  // namespace djinni_generated
