// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#pragma once

#include "djinni_support.hpp"
#include "register_response.hpp"

namespace djinni_generated {

class NativeRegisterResponse final {
public:
    using CppType = ::loginsystem::RegisterResponse;
    using JniType = jobject;

    using Boxed = NativeRegisterResponse;

    ~NativeRegisterResponse();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeRegisterResponse();
    friend ::djinni::JniClass<NativeRegisterResponse>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/loginsystem/RegisterResponse") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Z)V") };
    const jfieldID field_mSuccess { ::djinni::jniGetFieldID(clazz.get(), "mSuccess", "Z") };
};

}  // namespace djinni_generated
