// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#pragma once

#include "djinni_support.hpp"
#include "server_client.hpp"

namespace djinni_generated {

class NativeServerClient final : ::djinni::JniInterface<::loginsystem::ServerClient, NativeServerClient> {
public:
    using CppType = std::shared_ptr<::loginsystem::ServerClient>;
    using CppOptType = std::shared_ptr<::loginsystem::ServerClient>;
    using JniType = jobject;

    using Boxed = NativeServerClient;

    ~NativeServerClient();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeServerClient>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeServerClient>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeServerClient();
    friend ::djinni::JniClass<NativeServerClient>;
    friend ::djinni::JniInterface<::loginsystem::ServerClient, NativeServerClient>;

};

}  // namespace djinni_generated
