// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#import "TXSCheckSessionResponse.h"


@implementation TXSCheckSessionResponse

- (nonnull instancetype)initWithSuccess:(BOOL)success
                                isValid:(BOOL)isValid
{
    if (self = [super init]) {
        _success = success;
        _isValid = isValid;
    }
    return self;
}

+ (nonnull instancetype)checkSessionResponseWithSuccess:(BOOL)success
                                                isValid:(BOOL)isValid
{
    return [[self alloc] initWithSuccess:success
                                 isValid:isValid];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p success:%@ isValid:%@>", self.class, (void *)self, @(self.success), @(self.isValid)];
}

@end
