// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#import "TXSRegisterResponse.h"


@implementation TXSRegisterResponse

- (nonnull instancetype)initWithSuccess:(BOOL)success
{
    if (self = [super init]) {
        _success = success;
    }
    return self;
}

+ (nonnull instancetype)registerResponseWithSuccess:(BOOL)success
{
    return [[self alloc] initWithSuccess:success];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p success:%@>", self.class, (void *)self, @(self.success)];
}

@end
