// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#import "TXSCheckSessionResponse.h"
#import "TXSLoginResponse.h"
#import "TXSRegisterResponse.h"
#import <Foundation/Foundation.h>
@class TXSServerClient;


@interface TXSServerClient : NSObject

+ (nullable TXSServerClient *)create;

- (nonnull TXSRegisterResponse *)registerAccount:(nonnull NSString *)userName
                                        password:(nonnull NSString *)password;

- (nonnull TXSLoginResponse *)loginAccount:(nonnull NSString *)userName
                                  password:(nonnull NSString *)password;

- (nonnull TXSCheckSessionResponse *)checkSession:(nonnull NSString *)sessionId;

@end
