// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#include "server_client.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TXSServerClient;

namespace djinni_generated {

class ServerClient
{
public:
    using CppType = std::shared_ptr<::loginsystem::ServerClient>;
    using CppOptType = std::shared_ptr<::loginsystem::ServerClient>;
    using ObjcType = TXSServerClient*;

    using Boxed = ServerClient;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

