// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

package com.dropbox.loginsystem;

import android.support.annotation.NonNull;

/*package*/ final class CheckSessionResponse {


    /*package*/ final boolean mSuccess;

    /*package*/ final boolean mIsValid;

    public CheckSessionResponse(
            boolean success,
            boolean isValid) {
        this.mSuccess = success;
        this.mIsValid = isValid;
    }

    public boolean getSuccess() {
        return mSuccess;
    }

    public boolean getIsValid() {
        return mIsValid;
    }

    @Override
    public String toString() {
        return "CheckSessionResponse{" +
                "mSuccess=" + mSuccess +
                "," + "mIsValid=" + mIsValid +
        "}";
    }

}
