// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

package com.dropbox.loginsystem;

import android.support.annotation.NonNull;

/*package*/ final class RegisterResponse {


    /*package*/ final boolean mSuccess;

    public RegisterResponse(
            boolean success) {
        this.mSuccess = success;
    }

    public boolean getSuccess() {
        return mSuccess;
    }

    @Override
    public String toString() {
        return "RegisterResponse{" +
                "mSuccess=" + mSuccess +
        "}";
    }

}
