// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#import "TXSCheckSessionResponse.h"
#include "check_session_response.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TXSCheckSessionResponse;

namespace djinni_generated {

struct CheckSessionResponse
{
    using CppType = ::loginsystem::CheckSessionResponse;
    using ObjcType = TXSCheckSessionResponse*;

    using Boxed = CheckSessionResponse;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
