// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#import "TXSLoginResponse+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto LoginResponse::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Bool::toCpp(obj.success),
            ::djinni::String::toCpp(obj.sessionId)};
}

auto LoginResponse::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[TXSLoginResponse alloc] initWithSuccess:(::djinni::Bool::fromCpp(cpp.success))
                                           sessionId:(::djinni::String::fromCpp(cpp.session_id))];
}

}  // namespace djinni_generated
