// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#import "TXSRegisterResponse.h"
#include "register_response.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TXSRegisterResponse;

namespace djinni_generated {

struct RegisterResponse
{
    using CppType = ::loginsystem::RegisterResponse;
    using ObjcType = TXSRegisterResponse*;

    using Boxed = RegisterResponse;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
