// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#import <Foundation/Foundation.h>

@interface TXSRegisterResponse : NSObject
- (nonnull instancetype)initWithSuccess:(BOOL)success;
+ (nonnull instancetype)registerResponseWithSuccess:(BOOL)success;

@property (nonatomic, readonly) BOOL success;

@end
