// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

package com.dropbox.loginsystem;

import android.support.annotation.NonNull;

/*package*/ final class LoginResponse {


    /*package*/ final boolean mSuccess;

    /*package*/ final String mSessionId;

    public LoginResponse(
            boolean success,
            @NonNull String sessionId) {
        this.mSuccess = success;
        this.mSessionId = sessionId;
    }

    public boolean getSuccess() {
        return mSuccess;
    }

    @NonNull
    public String getSessionId() {
        return mSessionId;
    }

    @Override
    public String toString() {
        return "LoginResponse{" +
                "mSuccess=" + mSuccess +
                "," + "mSessionId=" + mSessionId +
        "}";
    }

}
