// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#pragma once

#include <string>
#include <utility>

namespace loginsystem {

struct LoginResponse final {
    bool success;
    std::string session_id;

    LoginResponse(bool success_,
                  std::string session_id_)
    : success(std::move(success_))
    , session_id(std::move(session_id_))
    {}
};

}  // namespace loginsystem
