// Code generated by protoc-gen-go. DO NOT EDIT.
// source: uni_login.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterReq struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_uni_login_b8f402cd27302b89, []int{0}
}
func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (dst *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(dst, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterResp struct {
	Errcode              int32    `protobuf:"varint,1,opt,name=errcode,proto3" json:"errcode,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_uni_login_b8f402cd27302b89, []int{1}
}
func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (dst *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(dst, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *RegisterResp) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

type LoginReq struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_uni_login_b8f402cd27302b89, []int{2}
}
func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (dst *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(dst, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResp struct {
	Errcode              int32    `protobuf:"varint,1,opt,name=errcode,proto3" json:"errcode,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	SessionId            string   `protobuf:"bytes,3,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_uni_login_b8f402cd27302b89, []int{3}
}
func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (dst *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(dst, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *LoginResp) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *LoginResp) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type CheckSessionReq struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckSessionReq) Reset()         { *m = CheckSessionReq{} }
func (m *CheckSessionReq) String() string { return proto.CompactTextString(m) }
func (*CheckSessionReq) ProtoMessage()    {}
func (*CheckSessionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_uni_login_b8f402cd27302b89, []int{4}
}
func (m *CheckSessionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckSessionReq.Unmarshal(m, b)
}
func (m *CheckSessionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckSessionReq.Marshal(b, m, deterministic)
}
func (dst *CheckSessionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckSessionReq.Merge(dst, src)
}
func (m *CheckSessionReq) XXX_Size() int {
	return xxx_messageInfo_CheckSessionReq.Size(m)
}
func (m *CheckSessionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckSessionReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckSessionReq proto.InternalMessageInfo

func (m *CheckSessionReq) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type CheckSessionResp struct {
	Errcode              int32    `protobuf:"varint,1,opt,name=errcode,proto3" json:"errcode,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	IsValid              bool     `protobuf:"varint,3,opt,name=isValid,proto3" json:"isValid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckSessionResp) Reset()         { *m = CheckSessionResp{} }
func (m *CheckSessionResp) String() string { return proto.CompactTextString(m) }
func (*CheckSessionResp) ProtoMessage()    {}
func (*CheckSessionResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_uni_login_b8f402cd27302b89, []int{5}
}
func (m *CheckSessionResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckSessionResp.Unmarshal(m, b)
}
func (m *CheckSessionResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckSessionResp.Marshal(b, m, deterministic)
}
func (dst *CheckSessionResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckSessionResp.Merge(dst, src)
}
func (m *CheckSessionResp) XXX_Size() int {
	return xxx_messageInfo_CheckSessionResp.Size(m)
}
func (m *CheckSessionResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckSessionResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckSessionResp proto.InternalMessageInfo

func (m *CheckSessionResp) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *CheckSessionResp) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *CheckSessionResp) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func init() {
	proto.RegisterType((*RegisterReq)(nil), "proto.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "proto.RegisterResp")
	proto.RegisterType((*LoginReq)(nil), "proto.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "proto.LoginResp")
	proto.RegisterType((*CheckSessionReq)(nil), "proto.CheckSessionReq")
	proto.RegisterType((*CheckSessionResp)(nil), "proto.CheckSessionResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UniLoginClient is the client API for UniLogin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UniLoginClient interface {
	// User login
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	// User register
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	// Check user session
	CheckSession(ctx context.Context, in *CheckSessionReq, opts ...grpc.CallOption) (*CheckSessionResp, error)
}

type uniLoginClient struct {
	cc *grpc.ClientConn
}

func NewUniLoginClient(cc *grpc.ClientConn) UniLoginClient {
	return &uniLoginClient{cc}
}

func (c *uniLoginClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, "/proto.UniLogin/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uniLoginClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, "/proto.UniLogin/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uniLoginClient) CheckSession(ctx context.Context, in *CheckSessionReq, opts ...grpc.CallOption) (*CheckSessionResp, error) {
	out := new(CheckSessionResp)
	err := c.cc.Invoke(ctx, "/proto.UniLogin/CheckSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UniLoginServer is the server API for UniLogin service.
type UniLoginServer interface {
	// User login
	Login(context.Context, *LoginReq) (*LoginResp, error)
	// User register
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	// Check user session
	CheckSession(context.Context, *CheckSessionReq) (*CheckSessionResp, error)
}

func RegisterUniLoginServer(s *grpc.Server, srv UniLoginServer) {
	s.RegisterService(&_UniLogin_serviceDesc, srv)
}

func _UniLogin_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniLoginServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UniLogin/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniLoginServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniLogin_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniLoginServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UniLogin/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniLoginServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniLogin_CheckSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniLoginServer).CheckSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UniLogin/CheckSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniLoginServer).CheckSession(ctx, req.(*CheckSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UniLogin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UniLogin",
	HandlerType: (*UniLoginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UniLogin_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _UniLogin_Register_Handler,
		},
		{
			MethodName: "CheckSession",
			Handler:    _UniLogin_CheckSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "uni_login.proto",
}

func init() { proto.RegisterFile("uni_login.proto", fileDescriptor_uni_login_b8f402cd27302b89) }

var fileDescriptor_uni_login_b8f402cd27302b89 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x52, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x65, 0x95, 0x6d, 0xb3, 0x63, 0x61, 0xcb, 0x08, 0x35, 0x2c, 0x1e, 0x64, 0x4f, 0xe2, 0xa1,
	0x82, 0xfd, 0x00, 0x45, 0xf1, 0x20, 0x88, 0x87, 0x88, 0x5e, 0x04, 0x65, 0xed, 0x86, 0x35, 0xd8,
	0x6e, 0x62, 0xa6, 0xc5, 0x9f, 0xf2, 0x23, 0x65, 0x37, 0x89, 0xed, 0x56, 0x4f, 0xf5, 0x94, 0xbc,
	0xf7, 0x32, 0x8f, 0x37, 0x33, 0x81, 0x74, 0x59, 0xab, 0x97, 0x99, 0xae, 0x54, 0x3d, 0x36, 0x56,
	0x2f, 0x34, 0xc6, 0xed, 0x91, 0x5f, 0xc3, 0x9e, 0x90, 0x95, 0xa2, 0x85, 0xb4, 0x42, 0x7e, 0x60,
	0x06, 0x6c, 0x49, 0xd2, 0xde, 0x15, 0x73, 0xc9, 0xa3, 0xa3, 0xe8, 0x38, 0x11, 0x3f, 0xb8, 0xd1,
	0x4c, 0x41, 0xf4, 0xa9, 0x6d, 0xc9, 0x77, 0x9c, 0x16, 0x70, 0x7e, 0x01, 0x83, 0x95, 0x0d, 0x19,
	0xe4, 0xd0, 0x97, 0xd6, 0x4e, 0x75, 0xe9, 0x6c, 0x62, 0x11, 0x20, 0x8e, 0xa0, 0x27, 0xad, 0x9d,
	0x53, 0xe5, 0x3d, 0x3c, 0xca, 0x2f, 0x81, 0xdd, 0x36, 0xf1, 0xfe, 0x93, 0xe2, 0x09, 0x12, 0xef,
	0xb1, 0x4d, 0x04, 0x3c, 0x84, 0x84, 0x24, 0x91, 0xd2, 0xf5, 0x4d, 0xc9, 0x77, 0x5b, 0x69, 0x45,
	0xe4, 0xa7, 0x90, 0x5e, 0xbd, 0xc9, 0xe9, 0xfb, 0xbd, 0x63, 0x9a, 0x9c, 0x9d, 0x82, 0x68, 0xb3,
	0xe0, 0x19, 0x86, 0xdd, 0x82, 0xad, 0x42, 0x71, 0xe8, 0x2b, 0x7a, 0x2c, 0x66, 0xca, 0x45, 0x62,
	0x22, 0xc0, 0xb3, 0xaf, 0x08, 0xd8, 0x43, 0xad, 0xda, 0x8e, 0xf1, 0x04, 0x62, 0x77, 0x49, 0xdd,
	0x7e, 0xc7, 0x61, 0x98, 0xd9, 0xb0, 0x4b, 0x90, 0xc1, 0x09, 0xb0, 0xb0, 0x2c, 0x44, 0xaf, 0xae,
	0x7d, 0x82, 0x6c, 0xff, 0x17, 0x47, 0x06, 0xcf, 0x61, 0xb0, 0xde, 0x0d, 0x8e, 0xfc, 0xa3, 0x8d,
	0x99, 0x64, 0x07, 0x7f, 0xf2, 0x64, 0x5e, 0x7b, 0x2d, 0x3f, 0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff,
	0xc7, 0x19, 0xf4, 0x55, 0x8a, 0x02, 0x00, 0x00,
}
