// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#include "NativeServerRequest.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeServerRequest::NativeServerRequest() = default;

NativeServerRequest::~NativeServerRequest() = default;

auto NativeServerRequest::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeServerRequest>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.request)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeServerRequest::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeServerRequest>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mRequest))};
}

}  // namespace djinni_generated
