// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#include "NativeServerResponse.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeServerResponse::NativeServerResponse() = default;

NativeServerResponse::~NativeServerResponse() = default;

auto NativeServerResponse::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeServerResponse>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.response)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeServerResponse::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeServerResponse>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mResponse))};
}

}  // namespace djinni_generated
