// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#include "NativeRequestCallback.hpp"  // my header
#include "NativeServerResponse.hpp"

namespace djinni_generated {

NativeRequestCallback::NativeRequestCallback() : ::djinni::JniInterface<::loginsystem::RequestCallback, NativeRequestCallback>() {}

NativeRequestCallback::~NativeRequestCallback() = default;

NativeRequestCallback::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeRequestCallback::JavaProxy::~JavaProxy() = default;

void NativeRequestCallback::JavaProxy::callback(const ::loginsystem::ServerResponse & c_response) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeRequestCallback>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_callback,
                           ::djinni::get(::djinni_generated::NativeServerResponse::fromCpp(jniEnv, c_response)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
