// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#include "NativeServerClient.hpp"  // my header
#include "NativeRequestCallback.hpp"
#include "NativeServerRequest.hpp"

namespace djinni_generated {

NativeServerClient::NativeServerClient() : ::djinni::JniInterface<::loginsystem::ServerClient, NativeServerClient>("com/dropbox/loginsystem/ServerClient$CppProxy") {}

NativeServerClient::~NativeServerClient() = default;


CJNIEXPORT void JNICALL Java_com_dropbox_loginsystem_ServerClient_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::loginsystem::ServerClient>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_dropbox_loginsystem_ServerClient_00024CppProxy_create(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        ::loginsystem::ServerClient::create();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_dropbox_loginsystem_ServerClient_00024CppProxy_request(JNIEnv* jniEnv, jobject /*this*/, jobject j_request, jobject j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        ::loginsystem::ServerClient::request(::djinni_generated::NativeServerRequest::toCpp(jniEnv, j_request),
                                             ::djinni_generated::NativeRequestCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
