// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#pragma once

#include "djinni_support.hpp"
#include "server_response.hpp"

namespace djinni_generated {

class NativeServerResponse final {
public:
    using CppType = ::loginsystem::ServerResponse;
    using JniType = jobject;

    using Boxed = NativeServerResponse;

    ~NativeServerResponse();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeServerResponse();
    friend ::djinni::JniClass<NativeServerResponse>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/loginsystem/ServerResponse") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;)V") };
    const jfieldID field_mResponse { ::djinni::jniGetFieldID(clazz.get(), "mResponse", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
