// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginsystem.djinni

#pragma once

#include "djinni_support.hpp"
#include "server_request.hpp"

namespace djinni_generated {

class NativeServerRequest final {
public:
    using CppType = ::loginsystem::ServerRequest;
    using JniType = jobject;

    using Boxed = NativeServerRequest;

    ~NativeServerRequest();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeServerRequest();
    friend ::djinni::JniClass<NativeServerRequest>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/loginsystem/ServerRequest") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;)V") };
    const jfieldID field_mRequest { ::djinni::jniGetFieldID(clazz.get(), "mRequest", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
